### ISSUE TITLE
‘antlr’ exception when parsing Tags 

### ISSUE THREAD

**Issue by biotech7** [BlueObelisk/chemicaltagger#8]
Hi,
     This issue may not a problem with chemicaltagger itself, but a compatiblity among various antlrs. so any tips of how to solve  it are desired. 
     when running [example](https://github.com/BlueObelisk/chemicaltagger) : `chemistrySentenceParser.parseTags()`. it raised a exception as follow :
OS : win10
IDE: IDEA
JDK: 1.8
antlr version: varies from 4.5.1 to 4.9.2(cannont decide which version can be compatible)
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at uk.ac.cam.ch.wwmm.chemicaltagger.ChemistrySentenceParser.parseTags(ChemistrySentenceParser.java:92)
	at com.jfinal.EngineTest.ChemicalTagger(EngineTest.java:1059)
	at com.jfinal.EngineTest.main(EngineTest.java:142)
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID ab35191a-1603-487e-b75a-479b831eaf6d (expected 59627784-3be5-417a-b9eb-8131a7286089 or a legacy UUID).
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:194)
	at uk.ac.cam.ch.wwmm.chemicaltagger.pregenerated.ChemicalChunkerLexer.<clinit>(ChemicalChunkerLexer.java:631)
	... 3 more
Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID ab35191a-1603-487e-b75a-479b831eaf6d (expected 59627784-3be5-417a-b9eb-8131a7286089 or a legacy UUID).
	... 5 more
```

**Comment by mjw99** [comment]
Unfortunately, I cannot reproduce this. I suspect it might be a function of your IDE; my knowledge of IntelliJ IDEA is quite limited.

**Comment by biotech7** [comment]
thanks for soon reply. i updated antlrs to 4.7.4 and it works well at current time.

**Comment by biotech7** [comment]
many tests passed when implementing antlr v4.7.4 by integration chemicaltagger source codes into my projects. thanks for your great works!
